version: '3.5'

networks:
  mop_network:
    name: mop_network

services:
  # local prometheus instance to collect data
  prometheus:
    container_name: 'mop-prometheus'
    image: prom/prometheus:v2.40.6
    volumes:
      - prometheusdata:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--enable-feature=agent'
      - '--config.file=/etc/prometheus/config.yml'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=info'
    ports:
      - 9090:9090
    networks:
      - mop_network
    restart: always

  # # local vmagent instance to collect data
  # vmagent:
  #   container_name: 'mop-vmagent'
  #   image: victoriametrics/vmagent:v1.85.0
  #   depends_on:
  #     - "vminsert"
  #   ports:
  #     - 8429:8429
  #   volumes:
  #     - vmagentdata:/vmagentdata
  #     - ./victoria-metrics/vmagent/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - "--promscrape.config=/etc/prometheus/prometheus.yml"
  #     - "--remoteWrite.url=http://vminsert:8480/insert/0/prometheus/api/v1/write"
  #   networks:
  #     - mop_network
  #   restart: always

  telegraf:
    build:
      context: './telegraf'
    container_name: 'mop-telegraf'
    hostname: mop-telegraf
    restart: 'always'
    ports:
      - '8125:8125/udp'
    networks:
      - mop_network

  sample-metrics:
    build:
      context: './sample-metrics'
    container_name: 'mop-sample-metrics'
    hostname: mop-sample-metrics
    restart: 'always'
    ports:
      - '8000:8000'
    networks:
      - mop_network

  # Grafana for vizualizing
  grafana:
    build:
      context: './grafana'
    container_name: 'mop-grafana'
    hostname: 'mop-grafana'
    restart: 'always'
    ports:
      - '3000:3000'
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    networks:
      - mop_network

  vmauth:
    container_name: 'mop-vmauth'
    image: victoriametrics/vmauth:v1.85.0
    # depends_on:
    #   - "vminsert"
    ports:
      - 8427:8427
    volumes:
      - ./victoria-metrics/vmauth/config.yml:/vmauth/config.yml
    command:
      - "--auth.config=/vmauth/config.yml"
    networks:
      - mop_network
    restart: always

  # Victoria metrics cluster
  vmstorage:
    container_name: 'mop-vmstorage'
    image: victoriametrics/vmstorage:v1.85.0-cluster
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata:/storage
    command:
      - '--storageDataPath=/storage'
    restart: always
    networks:
      - mop_network

  vminsert:
    container_name: 'mop-vminsert'
    image: victoriametrics/vminsert:v1.85.0-cluster
    depends_on:
      - "vmstorage"
    command:
      - '--storageNode=vmstorage:8400'
    ports:
      - 8480:8480
    restart: always
    networks:
      - mop_network

  vmselect:
    container_name: 'mop-vmselect'
    image: victoriametrics/vmselect:v1.85.0-cluster
    depends_on:
      - "vmstorage"
    command:
      - '--storageNode=vmstorage:8401'
      - '--vmalert.proxyURL=http://vmalert:8880'
    ports:
      - 8481:8481
    restart: always
    networks:
      - mop_network

  vmalert:
    container_name: 'mop-vmalert'
    image: victoriametrics/vmalert:v1.85.0
    depends_on:
      - "vmselect"
    ports:
      - 8880:8880
    volumes:
      - ./victoria-metrics/vmalert/alerts.yml:/etc/alerts/alerts.yml
    command:
      - '--datasource.url=http://vmselect:8481/select/0/prometheus'
      - '--remoteRead.url=http://vmselect:8481/select/0/prometheus'
      - '--remoteWrite.url=http://vminsert:8480/insert/0/prometheus'
      - '--notifier.url=http://alertmanager:9093/'
      - '--rule=/etc/alerts/*.yml'
      # display source of alerts in grafana
      - '-external.url=http://127.0.0.1:3000' #grafana outside container
      # when copypaste the line below be aware of '$$' for escaping in '$expr'
      - '--external.alert.source=explore?orgId=1&left=["now-1h","now","VictoriaMetrics",{"expr":"{{$$expr|quotesEscape|crlfEscape|queryEscape}}"},{"mode":"Metrics"},{"ui":[true,true,true,"none"]}]'
    restart: always
    networks:
      - mop_network

  alertmanager:
    container_name: 'mop-alertmanager'
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./victoria-metrics/alertmanager/alertmanager.yml:/config/alertmanager.yml
    command:
      - '--config.file=/config/alertmanager.yml'
    ports:
      - 9093:9093
    restart: always
    networks:
      - mop_network

# list of all the volumes used
volumes:
  prometheusdata: {} # used by prometheus agent
  vmagentdata: {}  # used by vmagent
  strgdata: {}   # used by vmstorage