global:
  scrape_interval: '10s'

scrape_configs:
  - job_name: "vmselect-self-check"
    static_configs:
      - targets: ['vmselect:8481']
        labels:
          group: 'selfcheck'

  - job_name: "vmalert-self-check"
    static_configs:
      - targets: ['vmalert:8880']
        labels:
          group: 'selfcheck'

  - job_name: "vminsert-self-check"
    static_configs:
      - targets: ['vminsert:8480']
        labels:
          group: 'selfcheck'

  - job_name: "vmagent-self-check"
    static_configs:
      - targets: ['vmagent:8429']
        labels:
          group: 'selfcheck'

  - job_name: "vmauth-self-check"
    static_configs:
      - targets: ['vmauth:8427']
        labels:
          group: 'selfcheck'

  - job_name: "sample-metrics"
    static_configs:
      - targets: ['sample-metrics:8000']
        labels:
          group: 'selfcheck'


  # node exporter to read sys stats from host machine
  - job_name: "node-exporter"
    # path to metrics
    metrics_path: '/metrics'
    static_configs:
      # the host.docker.internal refers to host machine.
      - targets: ['host.docker.internal:9100']
        labels:
          group: 'sys-stats-group'

remote_write:
  - url: 
    oauth2:
      client_id: 
      client_secret: 
      token_url: 
      # endpoint_params: 
        # grant_type: 'client_credentials'