{
 "title": "Sample Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sample statsd metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "statsd_dummy_gauge_1_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "statsd_dummy_gauge_1_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "statsd_dummy_gauge_2_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "statsd_dummy_gauge_2_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "statsd_dummy_counter_1_value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "statsd_dummy_counter_1_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "statsd_dummy_counter_2_value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "statsd_dummy_counter_2_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sample prometheus metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dummy Gauge 1",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "dummy_gauge_1", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Dummy Gauge 2",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "targets": [
      { "expr": "dummy_gauge_2", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "dummy_counter_1_total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "increase(dummy_counter_1_total)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "dummy_counter_2_total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "increase(dummy_counter_2_total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}